[package]
name = "gd_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro_rules_attribute = "*"
nom = "7.1.3"
num = "0.4.0"